name: Test Docker Setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-docker-setup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Test Docker Compose build
      run: |
        docker-compose config
        docker-compose build
        
    - name: Test application startup
      run: |
        docker-compose up -d
        sleep 30
        
    - name: Test application health
      run: |
        curl -f http://localhost:3000 || exit 1
        curl -f http://localhost:3000/api/posts || exit 1
        
    - name: View logs on failure
      if: failure()
      run: |
        docker-compose logs
        
    - name: Cleanup
      if: always()
      run: |
        docker-compose down -v
        
  test-local-development:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create environment file
      run: cp .env.example .env.local
      
    - name: Build application
      run: npm run build
      
    - name: Test application (mock database)
      run: |
        npm start &
        sleep 10
        curl -f http://localhost:3000 || exit 1
        curl -f http://localhost:3000/api/posts || exit 1
